### ISSUE TITLE
Privatizar Metodos

### ISSUE THREAD

**Issue by AndreiBudau** [SantiValentin/Practica_Issue#1]
hola, deberias de privatizar los metodos, en concreto los de la linea 
https://github.com/SantiValentin/Practica_Issue/blob/master/EurosADolares.java#L17
https://github.com/SantiValentin/Practica_Issue/blob/master/EurosADolares.java#L21

**Comment by SantiValentin** [comment]
tienes razon, no hay otra clase que los necesite
